const userConstant = {
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  ADD_USER_FAILURE: "ADD_USER_FAILURE",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAILURE: "DELETE_USER_FAILURE",
  FETCH_LIST_SUCCESS: "FETCH_LIST_SUCCESS",
  FETCH_LIST_FAILURE: "FETCH_LIST_FAILURE",
}

export default userConstant;